[package]
name = "tdlib-futures"
version = "0.1.0"
authors = ["Yuri Iozzelli <y.iozzelli@gmail.com>"]

[dependencies]
futures = "0.1.24"
serde = "1.0.78"
serde_json = "1.0.27"
serde_derive = "1.0.78"
tdjson-sys = "0.1.2"
tokio-core = "0.1.17"
anymap = "0.12.1"
