[package]
name = "tdlib-types"
version = "0.1.0"
authors = ["Yuri Iozzelli <y.iozzelli@gmail.com>"]

[dependencies]
serde = "1.0.78"
serde_json = "1.0.27"
serde_derive = "1.0.78"
serde-aux = "0.5.3"

[build-dependencies]
tl-codegen = { path = "../tl-codegen" }
